// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DalUsuarios.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DalUsuarios.Models
{
    public partial interface IPruebaTecnicaContextProcedures
    {
        Task<int> SpAddUsuariosAsync(string nombre, string apellido, string cedula, string correoElectronico, string contrasena, int? puntaje, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SpDeleteUsuarioAsync(int? idUsuario, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SpGetUsuariosResult>> SpGetUsuariosAsync(string cedula, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SpIniciarSesionResult>> SpIniciarSesionAsync(string correoElectronico, string contrasena, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SpRegistrarUsuarioResult>> SpRegistrarUsuarioAsync(string nombre, string apellido, string cedula, string correoElectronico, string contrasena, int? puntaje, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SpUpdateUsuariosAsync(string nombre, string apellido, string cedula, string correoElectronico, string contrasena, int? puntaje, int? idUsuario, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
