// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DalUsuarios.Models
{
    public partial class SpGetUsuariosResult
    {
        public int IdUsuario { get; set; }
        [StringLength(100)]
        public string Nombre { get; set; }
        [StringLength(100)]
        public string Apellido { get; set; }
        [StringLength(15)]
        public string Cedula { get; set; }
        [StringLength(100)]
        public string CorreoElectronico { get; set; }
        [StringLength(4000)]
        public string FechaHoraUIngreso { get; set; }
        [StringLength(300)]
        public string Contrasena { get; set; }
        public int? Puntaje { get; set; }
        public int? IdClasificacionUsuario { get; set; }
        [StringLength(100)]
        public string NombreClasificacion { get; set; }
        [StringLength(4000)]
        public string FechaCreacion { get; set; }
    }
}
