// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DalUsuarios.Models
{
    public partial class SpIniciarSesionResult
    {
        public bool? Ingreso { get; set; }
        public int? IdUsuario { get; set; }
    }
}
